{% set name = "gdtchron" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gdtchron-{{ version }}.tar.gz
  sha256: 68bcd3f4548cbce1b5b886299c72951f9af32bcdae6ecc6ee09e705197ad3a1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - tqdm
    - matplotlib-base
    - pyvista
    - scipy
    - joblib

test:
  imports:
    - gdtchron
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests --ignore=tests/test_visualization.py --ignore=tests/test_parallel_vtk.py

about:
  home: https://github.com/dyvasey/gdtchron
  summary: Thermochronology for geodynamic models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dyvasey
